### PR TITLE
Updated project file to support Visual Studio Express 2013

### PR DESCRIPTION
**Pull request by roskit**
This is the simplest way I found to fix the compilation issues. Tested with Visual Studio Express 2013 on Windows 8.

### CODE REVIEW

**Comment by grrrwaaa** [comment]
Looks good. The relative paths are necessary one way or another, as there is no reliably recommended location for the c74support folder in general, unfortunately.

**Comment by tap** [comment]
If you include the max SDK as a git submodule it may help? Not sure if that
is Appropriate here though?

On Monday, April 6, 2015, Graham Wakefield <notifications@github.com> wrote:

> Looks good. The relative paths are necessary one way or another, as there
> is no reliably recommended location for the c74support folder in general,
> unfortunately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grrrwaaa/maxcpp/pull/10#issuecomment-90093969>.
>


-- 
Best,
Tim

**Comment by grrrwaaa** [comment]
I've been tempted to do that, but the danger is ending up with a lot of copies of the Max SDK in the filesystem... seems better for the SDK to be side-by-side than inside a specific external's repo. Not fully convinced either way though. The absolute best solution would be to have consistent location for the SDK. Maybe even in the ~/Documents/Max 7/ folder...

**Comment by roskit** [comment]
@tap I also don't think this is appropriate. However, there are ways to override the C74SUPPORT path from the project itself, instead of relying on what's hard coded inside the Max SDK:
File max_extern_commons.props:
<C74SUPPORT>$(ProjectDir)..\..\..\c74support\</C74SUPPORT>

I'll looking into those Property Sheets in the coming days.

**Comment by tap** [comment]
I'm not sure it is a _danger_ per se. If your code is designed to use a specific version of the SDK, then your git repository should ideal point specifically to the SDK and version of that SDK for which you designed your code.

Anyway, there are pros and cons either way.

YMMV

**Pull request merged**
